#!/bin/bash
# set editor unless package is not installed

get_editor () {
    echo $1
    if [ -x $( which $1 ) ]
    then
        #printf "%s" $1    
        echo "true"
    else
        # if user passed editor does not exist - go with the default
        #printf "%s" $EDITOR
        echo "false"
    fi
}
