#!/bin/bash
# source include files

source_includes() {
    . $HOME/lib/directory_list
    #$1 = path
    #$2 = name filter
    get_files $1 $2
    #for f in $FILES
    #do
        #source $f
        echo $f
    #done
}
